In [8]:
import pyquil
from pyquil import Program, get_qc
from pyquil.gates import *
from pyquil.api import WavefunctionSimulator
import numpy as np

print("pyquil version = %s"%pyquil.__version__)

pyquil version = 2.0.0


In [2]:
# construct a Bell State program
p = Program(H(0), CNOT(0, 1))
qvm_str = '2q_qvm'
trials = 10
print('\nOriginal Program:')
print(p)



Original Program:
H 0
CNOT 0 1



In [3]:
#perform wave function analysis
print('Wave function when input |00>')
wf_sim = WavefunctionSimulator()
wavefunction = wf_sim.wavefunction(p)
output = wavefunction.get_outcome_probs()
for item in output:
    print("%s :  %s  "%(item,output[item]))

#Examine wave function with different input combinations
print('Wave function when input |01>')
p2 = Program(X(1))
p2 = p2+p
wfn2 = wf_sim.wavefunction(p2)
output2 = wfn2.get_outcome_probs()
for item in output2:
    print("%s :  %s  "%(item,output2[item]))
    
print('Wave function when input |10>')
p3 = Program(X(0))
p3 = p3+p
wfn3 = wf_sim.wavefunction(p3)
output3 = wfn3.get_outcome_probs()
for item in output3:
    print("%s :  %s  "%(item,output3[item]))
    
print('Wave function when input |11>')
p4 = Program(X(0),X(1))
p4 = p4+p
wfn4 = wf_sim.wavefunction(p4)
output4 = wfn4.get_outcome_probs()
for item in output4:
    print("%s :  %s  "%(item,output4[item]))

Wave function when input |00>
00 :  0.4999999999999999  
01 :  0.0  
10 :  0.0  
11 :  0.4999999999999999  
Wave function when input |01>
00 :  0.0  
01 :  0.4999999999999999  
10 :  0.4999999999999999  
11 :  0.0  
Wave function when input |10>
00 :  0.4999999999999999  
01 :  0.0  
10 :  0.0  
11 :  0.4999999999999999  
Wave function when input |11>
00 :  0.0  
01 :  0.4999999999999999  
10 :  0.4999999999999999  
11 :  0.0  


In [4]:
qc = get_qc(qvm_str) #get a QVM
#requests made to both quilc and qvm servers to compile and simulate/measure. 
result = qc.run_and_measure(p, trials=trials)

print('Results on %s after %s trials:'%(qvm_str,trials))
print('(run_and_measure function used here)\n')
for item in result:
    print('qubit %s values:'%(item))
    print(result[item])


Results on 2q_qvm after 10 trials:
(run_and_measure function used here)

qubit 0 values:
[0 0 1 0 1 1 1 0 0 1]
qubit 1 values:
[0 0 1 0 1 1 1 0 0 1]


In [5]:
print('\nNow we will compile!')
#two bit register (needed if you manually compile and run)
ro = p.declare('ro', 'BIT', 2)
p += MEASURE(0, ro[0])
p += MEASURE(1, ro[1])


executable = qc.compile(p) #create QC compatible specification
print('\nCompiled Program:')
print(executable['program'])

for i in range(0,trials):
    print('register values after run %s:'%(i))
    result2 = qc.run(executable)
    print(result2)


Now we will compile!

Compiled Program:
DECLARE ro BIT[2]
PRAGMA EXPECTED_REWIRING "#(0 1)"
RZ(pi/2) 0
RX(pi/2) 0
RZ(-pi/2) 1
RX(pi/2) 1
CZ 1 0
RX(-pi/2) 1
RZ(pi/2) 1
MEASURE 1 ro[1]
RZ(-pi/2) 0
MEASURE 0 ro[0]
PRAGMA CURRENT_REWIRING "#(0 1)"
HALT

register values after run 0:
[[1 1]]
register values after run 1:
[[0 0]]
register values after run 2:
[[0 0]]
register values after run 3:
[[0 0]]
register values after run 4:
[[0 0]]
register values after run 5:
[[1 1]]
register values after run 6:
[[1 1]]
register values after run 7:
[[0 0]]
register values after run 8:
[[0 0]]
register values after run 9:
[[1 1]]
